# Generated by Django 5.0.3 on 2024-04-01 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('Ph_no', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('QuantityAvailable', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('RouteID', models.AutoField(primary_key=True, serialize=False)),
                ('Origin', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EstimatedTravelTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AvailabilityStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderStatus', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.employee')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.order')),
            ],
            options={
                'unique_together': {('OrderID', 'EmployeeID')},
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.order')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.product')),
            ],
            options={
                'unique_together': {('OrderID', 'ProductID')},
            },
        ),
        migrations.CreateModel(
            name='VehicleRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RouteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.route')),
                ('VehicleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TL.vehicle')),
            ],
            options={
                'unique_together': {('VehicleID', 'RouteID')},
            },
        ),
    ]
